sudo: required
services:
  - docker

before_install:
  - docker build -t po/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run po/react-test npm test -- --coverage --watchAll=false

after_success:
   - docker build -t po/multi-client ./client
   - docker build -t po/multi-nginx ./nginx
   - docker build -t po/multi-server ./server
   - docker build -t po/multi-worker ./worker
   # Log in to the docker CLI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   # Take those images and push them to docker hub
   - docker push po/multi-client
   - docker push po/multi-nginx
   - docker push po/multi-server
   - docker push po/multi-worker
